version: '2'

services:
  postgres:
    image: postgres:10.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gavel
      - POSTGRES_USER=gavel
      - POSTGRES_PASSWORD=gavel
    restart: always

  redis:
    image: redis:5.0-alpine

  gavel:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: bash -c "python initialize.py && /usr/local/bin/gunicorn gavel:app -c workers.py"


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    user: nobody
    environment:
      - REDIS_URL=redis://redis/0
    depends_on:
      - gavel
      - redis
    ports:
        - "5555"
    command: celery -A gavel:celery worker

volumes:
  postgres_data: {}
